server.port=8082
spring.application.name=tarifa-service

spring.datasource.url=jdbc:postgresql://localhost:5433/tarifadb
spring.datasource.username=admin
spring.datasource.password=adminpassword
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update